/**
Ross Wagner
4/15/2018

This program takes in tokens generated by lexical.c and determines if the
PL/0 program is well formed (syntatically correct)

*/

#include "codes.h"
#include "parser.h"
#include "lexical.h"

#include <stdio.h>


/*
// for testing
int main(int argc, char** argv){

  if(argc != 2){
    printf("Usage: ./parse <PM0 source file>\n" );
    return ERROR;
  }
  // get lexem list



  //
  parse();

}
*/
void parse(){
  printf("%d\n", OK);
}
