/**
Ross Wagner
4/15/2018

This program takes in tokens generated by lexical.c and determines if the
PL/0 program is well formed (syntatically correct)

*/

#include "codes.h"
#include "parser.h"
#include "lexical.h"

#include <stdio.h>



// for testing
int main(int argc, char** argv){

  if(argc != 2){
    printf("Usage: ./parse <PM0 source file>\n" );
    return ERROR;
  }

  // get lexem list
  char * code = fileNameToStr(argv[1]);

  if(code == NULL){
    printf("Failed to read file");
    return ERROR;
  }

  //printf("%s", code);

  node * lexTable = NULL;
  lexTable = makeLexTable(&code);


  printLexTable(lexTable);

  //
  //parse();

}

void parse(){
  printf("%d\n", OK);
}
